/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/EPcRNONljCQ
 */
import { Button } from "@/components/ui/button";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

export function Component() {
  return (
    <div className="min-h-screen bg-gradient-to-r from-purple-300 via-pink-200 to-red-200 dark:from-gray-900 dark:via-gray-800 dark:to-gray-700">
      <nav className="bg-white shadow dark:bg-zinc-900">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between h-16">
            <div className="flex items-center">
              <img
                alt="Dreamz logo"
                className="h-10 w-10"
                height="40"
                src="/next.svg"
                style={{
                  aspectRatio: "40/40",
                  objectFit: "cover",
                }}
                width="40"
              />
              <div className="ml-8">
                <span className="font-semibold text-xl tracking-tight text-gray-700 dark:text-gray-200">
                  Dreamz
                </span>
              </div>
            </div>
            <div className="flex items-center space-x-4">
              <Button
                className="text-blue-500 border-blue-500 hover:bg-blue-500 hover:text-white dark:text-blue-400 dark:border-blue-400 dark:hover:bg-blue-400 dark:hover:text-white"
                variant="outline"
              >
                Login
              </Button>
              <Button
                className="text-blue-500 border-blue-500 hover:bg-blue-500 hover:text-white dark:text-blue-400 dark:border-blue-400 dark:hover:bg-blue-400 dark:hover:text-white"
                variant="outline"
              >
                Register
              </Button>
              <svg
                className=" h-6 w-6 text-gray-500 dark:text-gray-400"
                fill="none"
                height="24"
                stroke="currentColor"
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth="2"
                viewBox="0 0 24 24"
                width="24"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
                <circle cx="12" cy="7" r="4" />
              </svg>
            </div>
          </div>
        </div>
      </nav>
      <div className="w-full max-w-2xl mx-auto space-y-4 pt-16">
        <div className="text-center py-4">
          <h1 className="text-2xl font-semibold text-gray-700 dark:text-gray-200">
            Top G
          </h1>
        </div>
        <div className="bg-white shadow-md rounded-lg overflow-hidden dark:bg-zinc-900">
          <div className="px-6 py-4">
            <Accordion type="multiple">
              <AccordionItem value="item-1">
                <AccordionTrigger>Movies</AccordionTrigger>
                <AccordionContent>213</AccordionContent>
              </AccordionItem>
              <AccordionItem value="item-2">
                <AccordionTrigger>Youtube channels</AccordionTrigger>
                <AccordionContent>213</AccordionContent>
              </AccordionItem>
              <AccordionItem value="item-3">
                <AccordionTrigger>Youtube videos</AccordionTrigger>
                <AccordionContent>213</AccordionContent>
              </AccordionItem>
              <AccordionItem value="item-4">
                <AccordionTrigger>Telefilm</AccordionTrigger>
                <AccordionContent>213</AccordionContent>
              </AccordionItem>
              <AccordionItem value="item-5">
                <AccordionTrigger>Books</AccordionTrigger>
                <AccordionContent>213</AccordionContent>
              </AccordionItem>
            </Accordion>
          </div>
        </div>
      </div>
    </div>
  );
}
